
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: More Data Structures
site_description: Practice material for CSUF's CPSC 131
site_author: Oscar Olazabal
site_url: https://moredatastructures.com/

# Repository
repo_name: omolazabal/si-fall-2019
repo_url: https://github.com/omolazabal/si-fall-2019
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2019 Oscar Olazabal'

# Configuration
theme:
  name: null
  custom_dir: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "\uE80C"

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  disqus: 'cpsc-131-si'
  social:
    - type: github-alt
      link: https://github.com/omolazabal
    - type: linkedin
      link: https://linkedin.com/in/oscar-olazabal

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
      linenums: true
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Coding Exercises: set-up.md
  - SI Sessions: si-sessions.md
  - C++ Essentials:
    - Problems: essentials/problems.md
    - Coding Exercise: essentials/coding-exercise.md
    - Resources: essentials/resources.md
#   - Vectors:
#     - Problems: vectors/problems.md
#     - Coding Exercise: vectors/coding-exercise.md
#     - Resources: vectors/resources.md
#   - Linked Lists:
#     - Problems: linked-list/problems.md
#     - Coding Exercise: linked-list/coding-exercise.md
#     - Resources: linked-list/resources.md
#   - Stacks and Queues:
#     - Problems: stacks-queues/problems.md
#     - Coding Exercise: stacks-queues/coding-exercise.md
#     - Resources: stacks-queues/resources.md
#   - Trees:
#     - Problems: trees/problems.md
#     - Coding Exercise: trees/coding-exercise.md
#     - Resources: trees/resources.md
#   - Hash Tables:
#     - Problems: hash-tables/problems.md
#     - Coding Exercise: hash-tables/coding-exercise.md
#     - Resources: hash-tables/resources.md
#   - Graphs:
#     - Problems: graphs/problems.md
#     - Coding Exercise: graphs/coding-exercise.md
#     - Resources: graphs/resources.md

# Google Analytics
# google_analytics:
#   - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
#   - auto
